"""Mapping of all 204 operations to categories and function names."""

OPERATIONS = {
    # Case Transformations (16 ops)
    "Case/Text Transform": [
        ("Lowercase", "to_lowercase"),
        ("Uppercase", "to_uppercase"),
        ("Title Case", "to_title_case"),
        ("Camel Case", "to_camel_case"),
        ("Pascal Case", "to_pascal_case"),
        ("Snake Case", "to_snake_case"),
        ("Kebab Case", "to_kebab_case"),
        ("Constant Case", "to_constant_case"),
        ("Dot Case", "to_dot_case"),
        ("Path Case", "to_path_case"),
        ("Sentence Case", "to_sentence_case"),
        ("Swap Case", "swap_case"),
        ("Alternating Case", "to_alternating_case"),
        ("Sponge Case", "to_sponge_case"),
        ("Capitalize First Letter", "capitalize_first_letter"),
        ("Decapitalize First Letter", "decapitalize_first_letter"),
    ],

    # Reverse/Shuffle/Sort (13 ops)
    "Rearrange": [
        ("Reverse String", "reverse_string"),
        ("Reverse Words", "reverse_words"),
        ("Reverse Lines", "reverse_lines"),
        ("Shuffle Characters", "shuffle_characters"),
        ("Shuffle Words", "shuffle_words"),
        ("Shuffle Lines", "shuffle_lines"),
        ("Sort Characters (Ascending)", "sort_characters_asc"),
        ("Sort Characters (Descending)", "sort_characters_desc"),
        ("Sort Words (Ascending)", "sort_words_asc"),
        ("Sort Words (Descending)", "sort_words_desc"),
        ("Sort Lines (Ascending)", "sort_lines_asc"),
        ("Sort Lines (Descending)", "sort_lines_desc"),
        ("Sort Lines by Length", "sort_lines_by_length"),
    ],

    # Whitespace/Formatting (21 ops)
    "Format": [
        ("Trim", "trim"),
        ("Trim Left (Ltrim)", "trim_left"),
        ("Trim Right (Rtrim)", "trim_right"),
        ("Remove Extra Spaces", "remove_extra_spaces"),
        ("Remove All Whitespace", "remove_all_whitespace"),
        ("Remove Empty Lines", "remove_empty_lines"),
        ("Remove Duplicate Lines", "remove_duplicate_lines"),
        ("Remove Duplicate Words", "remove_duplicate_words"),
        ("Pad Left", "pad_left"),
        ("Pad Right", "pad_right"),
        ("Center Align", "center_align"),
        ("Left Align", "left_align"),
        ("Right Align", "right_align"),
        ("Justify", "justify"),
        ("Spaces to Tabs", "spaces_to_tabs"),
        ("Tabs to Spaces", "tabs_to_spaces"),
        ("Expand Tabs", "expand_tabs"),
        ("Wrap Text", "wrap_text"),
        ("Normalize Newlines (CRLF to LF)", "normalize_newlines_crlf_lf"),
        ("Normalize Newlines (LF to CRLF)", "normalize_newlines_lf_crlf"),
        ("Normalize Newlines (CR to LF)", "normalize_newlines_cr_lf"),
    ],

    # Encoding/Decoding (29 ops)
    "Encode/Decode": [
        ("Base64 Encode", "base64_encode"),
        ("Base64 Decode", "base64_decode"),
        ("Base64url Encode", "base64url_encode"),
        ("Base64url Decode", "base64url_decode"),
        ("URL Encode", "url_encode"),
        ("URL Decode", "url_decode"),
        ("HTML Entity Encode", "html_encode"),
        ("HTML Entity Decode", "html_decode"),
        ("Hex Encode", "hex_encode"),
        ("Hex Decode", "hex_decode"),
        ("Binary Encode", "binary_encode"),
        ("Binary Decode", "binary_decode"),
        ("Octal Encode", "octal_encode"),
        ("Octal Decode", "octal_decode"),
        ("Base32 Encode", "base32_encode"),
        ("Base32 Decode", "base32_decode"),
        ("Base58 Encode", "base58_encode"),
        ("Base58 Decode", "base58_decode"),
        ("Base85/Ascii85 Encode", "base85_encode"),
        ("Base85/Ascii85 Decode", "base85_decode"),
        ("Punycode Encode", "punycode_encode"),
        ("Punycode Decode", "punycode_decode"),
        ("Quoted-Printable Encode", "quoted_printable_encode"),
        ("Quoted-Printable Decode", "quoted_printable_decode"),
        ("ROT13", "rot13"),
        ("ROT47", "rot47"),
        ("Atbash Cipher", "atbash"),
        ("Caesar Cipher Encode", "caesar_cipher_encode"),
        ("Caesar Cipher Decode", "caesar_cipher_decode"),
    ],

    # Ciphers (3 ops)
    "Ciphers": [
        ("Vigenère Cipher Encode", "vigenere_cipher_encode"),
        ("Vigenère Cipher Decode", "vigenere_cipher_decode"),
        ("Morse Code Encode", "morse_encode"),
        ("Morse Code Decode", "morse_decode"),
    ],

    # Hashing/Checksums (33 ops)
    "Hash/Digest": [
        ("MD2 Hash", "hash_md2"),
        ("MD4 Hash", "hash_md4"),
        ("MD5 Hash", "hash_md5"),
        ("SHA-1 Hash", "hash_sha1"),
        ("SHA-224 Hash", "hash_sha224"),
        ("SHA-256 Hash", "hash_sha256"),
        ("SHA-384 Hash", "hash_sha384"),
        ("SHA-512 Hash", "hash_sha512"),
        ("SHA-512/224 Hash", "hash_sha512_224"),
        ("SHA-512/256 Hash", "hash_sha512_256"),
        ("SHA-3-224 Hash", "hash_sha3_224"),
        ("SHA-3-256 Hash", "hash_sha3_256"),
        ("SHA-3-384 Hash", "hash_sha3_384"),
        ("SHA-3-512 Hash", "hash_sha3_512"),
        ("Keccak-224 Hash", "hash_keccak_224"),
        ("Keccak-256 Hash", "hash_keccak_256"),
        ("Keccak-384 Hash", "hash_keccak_384"),
        ("Keccak-512 Hash", "hash_keccak_512"),
        ("Shake-128 Hash", "hash_shake128"),
        ("Shake-256 Hash", "hash_shake256"),
        ("BLAKE2b Hash", "hash_blake2b"),
        ("BLAKE2s Hash", "hash_blake2s"),
        ("BLAKE3 Hash", "hash_blake3"),
        ("RIPEMD-160 Hash", "hash_ripemd160"),
        ("Whirlpool Hash", "hash_whirlpool"),
        ("Tiger Hash", "hash_tiger"),
        ("CRC16", "hash_crc16"),
        ("CRC32", "hash_crc32"),
        ("Adler-32", "hash_adler32"),
        ("FNV-1a Hash", "hash_fnv1a"),
        ("MurmurHash", "hash_murmurhash"),
        ("xxHash", "hash_xxhash"),
    ],

    # HMAC/Key Derivation (6 ops)
    "Key Derivation": [
        ("HMAC-MD5", "hash_hmac_md5"),
        ("HMAC-SHA1", "hash_hmac_sha1"),
        ("HMAC-SHA256", "hash_hmac_sha256"),
        ("HMAC-SHA512", "hash_hmac_sha512"),
        ("Bcrypt Hash", "hash_bcrypt"),
        ("Scrypt Hash", "hash_scrypt"),
        ("Argon2 Hash", "hash_argon2"),
        ("PBKDF2 Hash", "hash_pbkdf2"),
    ],

    # Escaping/Unescaping (14 ops)
    "Escape/Unescape": [
        ("JSON Escape", "json_escape"),
        ("JSON Unescape", "json_unescape"),
        ("XML Escape", "xml_escape"),
        ("XML Unescape", "xml_unescape"),
        ("CSV Escape", "csv_escape"),
        ("CSV Unescape", "csv_unescape"),
        ("SQL Escape", "sql_escape"),
        ("Regex Escape", "regex_escape"),
        ("C String Escape", "c_string_escape"),
        ("C String Unescape", "c_string_unescape"),
        ("Java String Escape", "java_string_escape"),
        ("Java String Unescape", "java_string_unescape"),
        ("Python String Escape", "python_string_escape"),
        ("Python String Unescape", "python_string_unescape"),
        ("Bash Escape", "bash_escape"),
    ],

    # JSON/XML/SQL Formatting (10 ops)
    "JSON/Format": [
        ("Prettify JSON", "json_pretty_print"),
        ("Minify JSON", "json_minify"),
        ("Prettify XML", "xml_pretty_print"),
        ("Minify XML", "xml_minify"),
        ("Prettify SQL", "sql_pretty_print"),
        ("Minify SQL", "sql_minify"),
        ("Prettify CSS", "css_pretty_print"),
        ("Minify CSS", "css_minify"),
        ("Parse Query String", "parse_query_string"),
        ("Stringify Query String", "stringify_query_string"),
        ("JWT Decode", "jwt_decode"),
    ],

    # Statistics/Analysis (20 ops)
    "Statistics": [
        ("Character Count", "count_characters"),
        ("Character Count (No Spaces)", "count_characters_no_space"),
        ("Word Count", "count_words"),
        ("Line Count", "count_lines"),
        ("Byte Size (UTF-8)", "count_bytes"),
        ("Vowel Count", "count_vowels"),
        ("Consonant Count", "count_consonants"),
        ("Entropy Calculation", "shannon_entropy"),
        ("Levenshtein Distance", "levenshtein_distance"),
        ("Jaro-Winkler Distance", "jaro_winkler_distance"),
        ("Hamming Distance", "hamming_distance"),
        ("Soundex", "soundex"),
        ("Metaphone", "metaphone"),
        ("Double Metaphone", "double_metaphone"),
        ("Is Palindrome", "is_palindrome"),
        ("Is Anagram", "is_anagram"),
        ("Find Most Frequent Word", "find_most_frequent_word"),
        ("Find Most Frequent Character", "find_most_frequent_char"),
    ],

    # Extraction (13 ops)
    "Extract": [
        ("Extract Emails", "extract_emails"),
        ("Extract URLs", "extract_urls"),
        ("Extract Domains", "extract_domains"),
        ("Extract IPv4 Addresses", "extract_ipv4"),
        ("Extract IPv6 Addresses", "extract_ipv6"),
        ("Extract MAC Addresses", "extract_mac"),
        ("Extract Numbers", "extract_numbers"),
        ("Extract Hashtags", "extract_hashtags"),
        ("Extract Mentions", "extract_mentions"),
        ("Strip HTML Tags", "strip_html_tags"),
        ("Strip Markdown Tags", "strip_markdown_tags"),
        ("Strip Punctuation", "strip_punctuation"),
        ("Strip ANSI Escape Codes", "strip_ansi_codes"),
    ],

    # String Manipulation (10 ops)
    "Manipulate": [
        ("Split by Comma", "split_by_comma"),
        ("Split by Space", "split_by_space"),
        ("Split by Newline", "split_by_newline"),
        ("Join Lines by Comma", "join_by_comma"),
        ("Join Lines by Space", "join_by_space"),
        ("Chunk Text", "chunk_text"),
        ("Truncate Text", "truncate"),
        ("Add Prefix to Lines", "add_prefix_lines"),
        ("Add Suffix to Lines", "add_suffix_lines"),
        ("String to ASCII Array", "string_to_ascii_array"),
        ("ASCII Array to String", "ascii_array_to_string"),
    ],

    # Generation (11 ops)
    "Generate": [
        ("Zalgo Text Generator", "generate_zalgo"),
        ("Leetspeak Generator", "generate_leetspeak"),
        ("Upside Down Text", "generate_upside_down"),
        ("Vaporwave / Fullwidth Text", "generate_vaporwave"),
        ("Braille Translation", "generate_braille"),
        ("UUIDv4 Generator", "generate_uuid"),
        ("ULID Generator", "generate_ulid"),
        ("NanoID Generator", "generate_nanoid"),
        ("Random Password Generator", "generate_password"),
        ("Lorem Ipsum Generator", "generate_lorem_ipsum"),
        ("Slugify", "slugify"),
        ("Unslugify", "unslugify"),
    ],
}
