"""Shared utilities for string operations."""


def get_all_operations() -> dict:
    """Return all operations grouped by category."""
    return {
        'Transform': [
            ('To Uppercase', 'to_uppercase'),
            ('To Lowercase', 'to_lowercase'),
            ('To Title Case', 'to_title_case'),
            ('To Sentence Case', 'to_sentence_case'),
            ('Swap Case', 'swap_case'),
            ('CamelCase', 'to_camel_case'),
            ('PascalCase', 'to_pascal_case'),
            ('snake_case', 'to_snake_case'),
            ('kebab-case', 'to_kebab_case'),
            ('CONSTANT_CASE', 'to_constant_case'),
            ('Reverse', 'reverse_string'),
            ('Reverse Words', 'reverse_words'),
            ('Reverse Lines', 'reverse_lines'),
            ('Rotate N Characters', 'rotate_chars'),
            ('Repeat N Times', 'repeat_string'),
            ('Dot Case', 'to_dot_case'),
            ('Path Case', 'to_path_case'),
            ('Alternating Case', 'to_alternating_case'),
            ('Sponge Case', 'to_sponge_case'),
            ('Capitalize First', 'capitalize_first_letter'),
            ('Decapitalize First', 'decapitalize_first_letter'),
        ],
        'Encode/Decode': [
            ('Base64 Encode', 'base64_encode'),
            ('Base64 Decode', 'base64_decode'),
            ('Base64url Encode', 'base64url_encode'),
            ('Base64url Decode', 'base64url_decode'),
            ('Base32 Encode', 'base32_encode'),
            ('Base32 Decode', 'base32_decode'),
            ('Base58 Encode', 'base58_encode'),
            ('Base58 Decode', 'base58_decode'),
            ('Base85 Encode', 'base85_encode'),
            ('Base85 Decode', 'base85_decode'),
            ('Punycode Encode', 'punycode_encode'),
            ('Punycode Decode', 'punycode_decode'),
            ('Quoted-Printable Encode', 'quoted_printable_encode'),
            ('Quoted-Printable Decode', 'quoted_printable_decode'),
            ('ROT47', 'rot47'),
            ('Caesar Cipher Encode', 'caesar_cipher_encode'),
            ('Caesar Cipher Decode', 'caesar_cipher_decode'),
            ('Vigenère Cipher Encode', 'vigenere_cipher_encode'),
            ('Vigenère Cipher Decode', 'vigenere_cipher_decode'),
            ('Morse Code Encode', 'morse_encode'),
            ('Morse Code Decode', 'morse_decode'),
            ('URL Encode', 'url_encode'),
            ('URL Decode', 'url_decode'),
            ('HTML Entity Encode', 'html_encode'),
            ('HTML Entity Decode', 'html_decode'),
            ('Hex Encode', 'hex_encode'),
            ('Hex Decode', 'hex_decode'),
            ('ROT13', 'rot13'),
            ('Unicode Escape', 'unicode_escape'),
            ('Unicode Unescape', 'unicode_unescape'),
            ('Binary Encode', 'binary_encode'),
            ('Binary Decode', 'binary_decode'),
            ('Octal Encode', 'octal_encode'),
            ('Octal Decode', 'octal_decode'),
        ],
        'JSON': [
            ('JSON Escape', 'json_escape'),
            ('JSON Unescape', 'json_unescape'),
            ('JSON Pretty Print', 'json_pretty_print'),
            ('JSON Minify', 'json_minify'),
            ('JSON to String', 'json_to_string'),
            ('String to JSON', 'string_to_json'),
            ('JSON Diff', 'json_diff'),
            ('JSON Path Extract', 'json_path_extract'),
            ('XML Pretty Print', 'xml_pretty_print'),
            ('XML Minify', 'xml_minify'),
            ('SQL Pretty Print', 'sql_pretty_print'),
            ('SQL Minify', 'sql_minify'),
            ('CSS Pretty Print', 'css_pretty_print'),
            ('CSS Minify', 'css_minify'),
            ('Parse Query String', 'parse_query_string'),
            ('Stringify Query String', 'stringify_query_string'),
            ('JWT Decode', 'jwt_decode'),
        ],
        'Format': [
            ('Trim (both)', 'trim'),
            ('Trim Left', 'trim_left'),
            ('Trim Right', 'trim_right'),
            ('Trim Newlines', 'trim_newlines'),
            ('Collapse Whitespace', 'collapse_whitespace'),
            ('Remove Empty Lines', 'remove_empty_lines'),
            ('Remove Duplicate Lines', 'remove_duplicate_lines'),
            ('Sort Lines', 'sort_lines'),
            ('Deduplicate Lines', 'deduplicate_lines'),
            ('Indent', 'indent_text'),
            ('Unindent', 'unindent_text'),
            ('Wrap Text', 'wrap_text'),
            ('Replace Line Endings', 'replace_line_endings'),
            ('Normalize Unicode', 'normalize_unicode'),
            ('Strip Non-ASCII', 'strip_non_ascii'),
            ('Remove Diacritics', 'remove_diacritics'),
            ('Slugify', 'slugify'),
            ('Truncate', 'truncate'),
            ('Pad Left', 'pad_left'),
            ('Pad Right', 'pad_right'),
            ('Center Align', 'center_align'),
            ('Left Align', 'left_align'),
            ('Right Align', 'right_align'),
            ('Justify', 'justify'),
            ('Remove All Whitespace', 'remove_all_whitespace'),
            ('Remove Duplicate Words', 'remove_duplicate_words'),
            ('Spaces to Tabs', 'spaces_to_tabs'),
            ('Tabs to Spaces', 'tabs_to_spaces'),
            ('Expand Tabs', 'expand_tabs'),
            ('CRLF to LF', 'normalize_newlines_crlf_lf'),
            ('LF to CRLF', 'normalize_newlines_lf_crlf'),
            ('CR to LF', 'normalize_newlines_cr_lf'),
            ('Add Line Numbers', 'add_line_numbers'),
            ('Remove Line Numbers', 'remove_line_numbers'),
            ('Extract Lines', 'extract_lines'),
            ('Repeat Lines N Times', 'repeat_lines'),
        ],
        'Find & Replace': [
            ('Find and Replace', 'find_and_replace'),
            ('Find and Replace All', 'find_and_replace_all'),
            ('Regex Find', 'regex_find'),
            ('Regex Replace', 'regex_replace'),
            ('Count Matches', 'count_matches'),
            ('Extract Regex Groups', 'extract_regex_groups'),
        ],
        'Extract': [
            ('Extract Emails', 'extract_emails'),
            ('Extract URLs', 'extract_urls'),
            ('Extract Phone Numbers', 'extract_phone_numbers'),
            ('Extract IP Addresses', 'extract_ip_addresses'),
            ('Extract Dates', 'extract_dates'),
            ('Extract Between Markers', 'extract_between_markers'),
            ('Extract by Regex', 'extract_regex'),
            ('Extract First N Chars', 'extract_first_n'),
            ('Extract Last N Chars', 'extract_last_n'),
            ('Extract by Line Range', 'extract_by_line_range'),
        ],
        'Hash/Digest': [
            ('MD5', 'hash_md5'),
            ('SHA-1', 'hash_sha1'),
            ('SHA-256', 'hash_sha256'),
            ('SHA-512', 'hash_sha512'),
            ('CRC32', 'hash_crc32'),
            ('HMAC', 'hash_hmac'),
            # New hash functions
            ('MD2', 'hash_md2'),
            ('MD4', 'hash_md4'),
            ('SHA-224', 'hash_sha224'),
            ('SHA-384', 'hash_sha384'),
            ('SHA-512/224', 'hash_sha512_224'),
            ('SHA-512/256', 'hash_sha512_256'),
            ('SHA-3-224', 'hash_sha3_224'),
            ('SHA-3-256', 'hash_sha3_256'),
            ('SHA-3-384', 'hash_sha3_384'),
            ('SHA-3-512', 'hash_sha3_512'),
            ('Keccak-224', 'hash_keccak_224'),
            ('Keccak-256', 'hash_keccak_256'),
            ('Keccak-384', 'hash_keccak_384'),
            ('Keccak-512', 'hash_keccak_512'),
            ('Shake-128', 'hash_shake128'),
            ('Shake-256', 'hash_shake256'),
            ('BLAKE2b', 'hash_blake2b'),
            ('BLAKE2s', 'hash_blake2s'),
            ('BLAKE3', 'hash_blake3'),
            ('RIPEMD-160', 'hash_ripemd160'),
            ('Whirlpool', 'hash_whirlpool'),
            ('Tiger', 'hash_tiger'),
            ('CRC16', 'hash_crc16'),
            ('FNV-1a', 'hash_fnv1a'),
            ('MurmurHash', 'hash_murmurhash'),
            ('xxHash', 'hash_xxhash'),
            ('HMAC-MD5', 'hash_hmac_md5'),
            ('HMAC-SHA1', 'hash_hmac_sha1'),
            ('HMAC-SHA256', 'hash_hmac_sha256'),
            ('HMAC-SHA512', 'hash_hmac_sha512'),
            ('Bcrypt', 'hash_bcrypt'),
            ('Scrypt', 'hash_scrypt'),
            ('Argon2', 'hash_argon2'),
            ('PBKDF2', 'hash_pbkdf2'),
        ],
        'Statistics': [
            ('Count Characters', 'count_characters'),
            ('Count Characters (no space)', 'count_characters_no_space'),
            ('Count Words', 'count_words'),
            ('Count Lines', 'count_lines'),
            ('Count Bytes', 'count_bytes'),
            ('Character Frequency', 'character_frequency'),
            ('Word Frequency', 'word_frequency'),
            ('Shannon Entropy', 'shannon_entropy'),
            ('Palindrome Check', 'is_palindrome'),
            ('Levenshtein Distance', 'levenshtein_distance'),
            ('Longest Word', 'longest_word'),
            ('Shortest Word', 'shortest_word'),
            ('Unique Words', 'count_unique_words'),
            ('Readability Score', 'readability_score'),
            ('Count Vowels', 'count_vowels'),
            ('Count Consonants', 'count_consonants'),
            ('Jaro-Winkler Distance', 'jaro_winkler_distance'),
            ('Hamming Distance', 'hamming_distance'),
            ('Soundex', 'soundex'),
            ('Metaphone', 'metaphone'),
            ('Double Metaphone', 'double_metaphone'),
            ('Is Anagram', 'is_anagram'),
            ('Most Frequent Word', 'find_most_frequent_word'),
            ('Most Frequent Character', 'find_most_frequent_char'),
        ],
        'Misc': [
            ('Compare Two Texts', 'diff_texts'),
            ('Generate UUID', 'generate_uuid'),
            ('Generate Password', 'generate_password'),
            ('Generate Lorem Ipsum', 'generate_lorem_ipsum'),
            ('Generate Sequence', 'generate_sequence'),
            ('Pig Latin', 'pig_latin'),
            ('Atbash Cipher', 'atbash'),
            ('Affine Cipher', 'affine_cipher'),
        ],
        'Rearrange': [
            ('Shuffle Characters', 'shuffle_characters'),
            ('Shuffle Words', 'shuffle_words'),
            ('Shuffle Lines', 'shuffle_lines'),
            ('Sort Characters Asc', 'sort_characters_asc'),
            ('Sort Characters Desc', 'sort_characters_desc'),
            ('Sort Words Asc', 'sort_words_asc'),
            ('Sort Words Desc', 'sort_words_desc'),
            ('Sort Lines Asc', 'sort_lines_asc'),
            ('Sort Lines Desc', 'sort_lines_desc'),
            ('Sort Lines By Length', 'sort_lines_by_length'),
        ],
        'Escape/Unescape': [
            ('JSON Escape', 'json_escape'),
            ('JSON Unescape', 'json_unescape'),
            ('XML Escape', 'xml_escape'),
            ('XML Unescape', 'xml_unescape'),
            ('CSV Escape', 'csv_escape'),
            ('CSV Unescape', 'csv_unescape'),
            ('SQL Escape', 'sql_escape'),
            ('SQL Unescape', 'sql_unescape'),
            ('Regex Escape', 'regex_escape'),
            ('C String Escape', 'c_string_escape'),
            ('C String Unescape', 'c_string_unescape'),
            ('Java String Escape', 'java_string_escape'),
            ('Java String Unescape', 'java_string_unescape'),
            ('Python String Escape', 'python_string_escape'),
            ('Python String Unescape', 'python_string_unescape'),
            ('Bash Escape', 'bash_escape'),
        ],
        'Extract': [
            ('Extract Emails', 'extract_emails'),
            ('Extract URLs', 'extract_urls'),
            ('Extract Phone Numbers', 'extract_phone_numbers'),
            ('Extract IP Addresses', 'extract_ip_addresses'),
            ('Extract Domains', 'extract_domains'),
            ('Extract IPv6', 'extract_ipv6'),
            ('Extract MAC', 'extract_mac'),
            ('Extract Numbers', 'extract_numbers'),
            ('Extract Hashtags', 'extract_hashtags'),
            ('Extract Mentions', 'extract_mentions'),
            ('Strip HTML Tags', 'strip_html_tags'),
            ('Strip Markdown Tags', 'strip_markdown_tags'),
            ('Strip Punctuation', 'strip_punctuation'),
            ('Strip ANSI Codes', 'strip_ansi_codes'),
            ('Extract Dates', 'extract_dates'),
            ('Extract Between Markers', 'extract_between_markers'),
            ('Extract by Regex', 'extract_regex'),
            ('Extract First N Chars', 'extract_first_n'),
            ('Extract Last N Chars', 'extract_last_n'),
            ('Extract by Line Range', 'extract_by_line_range'),
        ],
        'Manipulate': [
            ('Split by Comma', 'split_by_comma'),
            ('Split by Space', 'split_by_space'),
            ('Split by Newline', 'split_by_newline'),
            ('Join by Comma', 'join_by_comma'),
            ('Join by Space', 'join_by_space'),
            ('Chunk Text', 'chunk_text'),
            ('Add Prefix Lines', 'add_prefix_lines'),
            ('Add Suffix Lines', 'add_suffix_lines'),
            ('String to ASCII Array', 'string_to_ascii_array'),
            ('ASCII Array to String', 'ascii_array_to_string'),
        ],
        'Generate': [
            ('Zalgo Text', 'generate_zalgo'),
            ('Leetspeak', 'generate_leetspeak'),
            ('Upside Down Text', 'generate_upside_down'),
            ('Vaporwave Text', 'generate_vaporwave'),
            ('Braille', 'generate_braille'),
            ('ULID', 'generate_ulid'),
            ('NanoID', 'generate_nanoid'),
            ('Unslugify', 'unslugify'),
            ('UUIDv4', 'generate_uuid'),
            ('Password', 'generate_password'),
            ('Lorem Ipsum', 'generate_lorem_ipsum'),
            ('Slugify', 'slugify'),
        ],
    }
