"""Shared utilities for string operations."""


def get_all_operations() -> dict:
    """Return all operations grouped by category."""
    return {
        'Transform': [
            ('To Uppercase', 'to_uppercase'),
            ('To Lowercase', 'to_lowercase'),
            ('To Title Case', 'to_title_case'),
            ('To Sentence Case', 'to_sentence_case'),
            ('Swap Case', 'swap_case'),
            ('CamelCase', 'to_camel_case'),
            ('PascalCase', 'to_pascal_case'),
            ('snake_case', 'to_snake_case'),
            ('kebab-case', 'to_kebab_case'),
            ('CONSTANT_CASE', 'to_constant_case'),
            ('Reverse', 'reverse_string'),
            ('Reverse Words', 'reverse_words'),
            ('Reverse Lines', 'reverse_lines'),
            ('Rotate N Characters', 'rotate_chars'),
            ('Repeat N Times', 'repeat_string'),
        ],
        'Encode/Decode': [
            ('Base64 Encode', 'base64_encode'),
            ('Base64 Decode', 'base64_decode'),
            ('URL Encode', 'url_encode'),
            ('URL Decode', 'url_decode'),
            ('HTML Entity Encode', 'html_encode'),
            ('HTML Entity Decode', 'html_decode'),
            ('Hex Encode', 'hex_encode'),
            ('Hex Decode', 'hex_decode'),
            ('ROT13', 'rot13'),
            ('Unicode Escape', 'unicode_escape'),
            ('Unicode Unescape', 'unicode_unescape'),
            ('Binary Encode', 'binary_encode'),
            ('Binary Decode', 'binary_decode'),
            ('Octal Encode', 'octal_encode'),
            ('Octal Decode', 'octal_decode'),
        ],
        'JSON': [
            ('JSON Escape', 'json_escape'),
            ('JSON Unescape', 'json_unescape'),
            ('JSON Pretty Print', 'json_pretty_print'),
            ('JSON Minify', 'json_minify'),
            ('JSON to String', 'json_to_string'),
            ('String to JSON', 'string_to_json'),
            ('JSON Diff', 'json_diff'),
            ('JSON Path Extract', 'json_path_extract'),
        ],
        'Format': [
            ('Trim (both)', 'trim'),
            ('Trim Left', 'trim_left'),
            ('Trim Right', 'trim_right'),
            ('Trim Newlines', 'trim_newlines'),
            ('Collapse Whitespace', 'collapse_whitespace'),
            ('Remove Empty Lines', 'remove_empty_lines'),
            ('Remove Duplicate Lines', 'remove_duplicate_lines'),
            ('Sort Lines', 'sort_lines'),
            ('Deduplicate Lines', 'deduplicate_lines'),
            ('Indent', 'indent_text'),
            ('Unindent', 'unindent_text'),
            ('Wrap Text', 'wrap_text'),
            ('Replace Line Endings', 'replace_line_endings'),
            ('Normalize Unicode', 'normalize_unicode'),
            ('Strip Non-ASCII', 'strip_non_ascii'),
            ('Remove Diacritics', 'remove_diacritics'),
            ('Slugify', 'slugify'),
            ('Truncate', 'truncate'),
            ('Pad Left', 'pad_left'),
            ('Pad Right', 'pad_right'),
            ('Add Line Numbers', 'add_line_numbers'),
            ('Remove Line Numbers', 'remove_line_numbers'),
            ('Extract Lines', 'extract_lines'),
            ('Repeat Lines N Times', 'repeat_lines'),
        ],
        'Find & Replace': [
            ('Find and Replace', 'find_and_replace'),
            ('Find and Replace All', 'find_and_replace_all'),
            ('Regex Find', 'regex_find'),
            ('Regex Replace', 'regex_replace'),
            ('Count Matches', 'count_matches'),
            ('Extract Regex Groups', 'extract_regex_groups'),
        ],
        'Extract': [
            ('Extract Emails', 'extract_emails'),
            ('Extract URLs', 'extract_urls'),
            ('Extract Phone Numbers', 'extract_phone_numbers'),
            ('Extract IP Addresses', 'extract_ip_addresses'),
            ('Extract Dates', 'extract_dates'),
            ('Extract Between Markers', 'extract_between_markers'),
            ('Extract by Regex', 'extract_regex'),
            ('Extract First N Chars', 'extract_first_n'),
            ('Extract Last N Chars', 'extract_last_n'),
            ('Extract by Line Range', 'extract_by_line_range'),
        ],
        'Hash/Digest': [
            ('MD5', 'hash_md5'),
            ('SHA-1', 'hash_sha1'),
            ('SHA-256', 'hash_sha256'),
            ('SHA-512', 'hash_sha512'),
            ('CRC32', 'hash_crc32'),
            ('HMAC', 'hash_hmac'),
        ],
        'Statistics': [
            ('Count Characters', 'count_characters'),
            ('Count Characters (no space)', 'count_characters_no_space'),
            ('Count Words', 'count_words'),
            ('Count Lines', 'count_lines'),
            ('Count Bytes', 'count_bytes'),
            ('Character Frequency', 'character_frequency'),
            ('Word Frequency', 'word_frequency'),
            ('Shannon Entropy', 'shannon_entropy'),
            ('Palindrome Check', 'is_palindrome'),
            ('Levenshtein Distance', 'levenshtein_distance'),
            ('Longest Word', 'longest_word'),
            ('Shortest Word', 'shortest_word'),
            ('Unique Words', 'count_unique_words'),
            ('Readability Score', 'readability_score'),
        ],
        'Misc': [
            ('Compare Two Texts', 'diff_texts'),
            ('Generate UUID', 'generate_uuid'),
            ('Generate Password', 'generate_password'),
            ('Generate Lorem Ipsum', 'generate_lorem_ipsum'),
            ('Generate Sequence', 'generate_sequence'),
            ('Text to Morse Code', 'text_to_morse'),
            ('Morse to Text', 'morse_to_text'),
            ('Pig Latin', 'pig_latin'),
            ('Atbash Cipher', 'atbash'),
            ('Vigenere Cipher', 'vigenere_cipher'),
            ('Affine Cipher', 'affine_cipher'),
        ],
    }
